---
- name: build nginx, enroll / update cert, configure site
  hosts: web-vm
  become: true

  vars:
    nginx_version: 'nginx-1.28.0'
    site_name: "test"
    trusted_network: "192.168.100.2"
    enroll_cert: false
    certbot_email: 'PASS_AS_ENV_OR_VAR'
    maxmind_account_id: 'PASS_AS_ENV_OR_VAR'
    maxmind_license_key: 'PASS_AS_ENV_OR_VAR'

  roles:
    - build_nginx
