---
dev_packages:
  - name: 'libpcre2-dev'
  - name: 'libssl-dev'
  - name: 'zlib1g-dev'
  - name: 'libxslt1-dev'
  - name: 'libxml2-dev'
  - name: 'libgd-dev'
  - name: 'libperl-dev'
module_packages:
  - name: 'libgd3'
  - name: 'libxslt1.1'
nginx_modules_config:
  - filename: '50-mod-http-geoip2.conf'
    content: 'load_module modules/ngx_http_geoip2_module.so;'
  - filename: '50-mod-http-image-filter.conf'
    content: 'load_module modules/ngx_http_image_filter_module.so;'
  - filename: '50-mod-http-perl.conf'
    content: 'load_module modules/ngx_http_perl_module.so;'
  - filename: '50-mod-http-xslt-filter.conf'
    content: 'load_module modules/ngx_http_xslt_filter_module.so;'
  - filename: '50-mod-mail.conf'
    content: 'load_module modules/ngx_mail_module.so;'
  - filename: '50-mod-stream.conf'
    content: 'load_module modules/ngx_stream_module.so;'
  - filename: '70-mod-stream-geoip2.conf'
    content: 'load_module modules/ngx_stream_geoip2_module.so;'
nginx_configure_params: "--with-cc-opt='-g -O2 -ffile-prefix-map=/build/reproducible-path/{{ nginx_version }}=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' --sbin-path=/usr/sbin/nginx --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=stderr --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-compat --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_secure_link_module --with-http_sub_module --with-mail_ssl_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-stream_realip_module --with-http_image_filter_module=dynamic --with-http_perl_module=dynamic --with-http_xslt_module=dynamic --with-mail=dynamic --with-stream=dynamic --add-dynamic-module=../ngx_http_geoip2_module --add-module=../headers-more-nginx-module --add-module=../nginx-module-vts"
