all:
  children:
    esxi:
      hosts:
        hv-02: {}
      vars:
        ansible_python_interpreter: /bin/python3
        esxi_ip: "PASS_AS_ENV_OR_VAR"
        esxi_user: "PASS_AS_ENV_OR_VAR"
        esxi_passwd: "PASS_AS_ENV_OR_VAR"
        esxi_hostname: "PASS_AS_ENV_OR_VAR"
        datastore_path: "PASS_AS_ENV_OR_VAR"

    cloned_vm:
      hosts:
        192.168.100.100: {}
