---
- name: copy interfaces config file and apply
  template:
    src: "{{ target_name }}.j2"
    dest: /etc/network/interfaces
  notify: restart networking

- name: add cloned VM to inventory
  add_host:
    name: "{{ clone_name }}"
    ansible_host: "{{ ip_address }}"
    groups: cloned_vm
  changed_when: false
